### ISSUE TITLE
Additional tools: kubens, kubectx, s2i

### ISSUE THREAD

**Issue by tomasliumparas** [ksandermann/cloud-toolbox#21]
Would be nice to also see this included:
https://github.com/ahmetb/kubectx/
https://github.com/openshift/source-to-image

`kubens` lets to switch namespaces easily
`kubectx` lets to switch context easily

`s2i` docker image build framework by making builder images which run on OpenShift

**Comment by ksandermann** [comment]
As an alternative to kubectx I already built 3 bash aliases inside autoexec.sh

"kgc" lists the context
"ksc mycontext" sets/switches the context
"ksn mynamespace" sets/switches the namespace in the current context

Are the features in kubectx that are not covered by this and would be of interest?

s2i I am aware of and I actually did not include it on purpose, as I think the toolbox should not be used in actual pipelines (as it is not hardened) - or were you thinking about using it locally to test around ? I could include it for that ofcourse
